on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    steps:
      - uses: actions/checkout@v3 
      - run: |
          cd business_logic
          make check
  build:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    needs: [check]
    steps:
      - uses: actions/checkout@v3 
      - run: | 
            cd business_logic
            make build