on: [push, pull_request]

jobs:
  preparing:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    steps:
      - run: |
        apt update
        apt get-install lcov
  check:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    steps:
      - uses: actions/checkout@v3 
      - run: make check
  build:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    needs: [check]
    steps:
      - uses: actions/checkout@v3 
      - run: make build
  test:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - run: make test
      - name: save server report artifact
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: ./build/report/

  memtest:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    needs: [build]
    steps:
      - uses: actions/checkout@v3 
      - run: make memtest
      - name: save valgrind logs artifact
        uses: actions/upload-artifact@v3
        with:
          name: valgrind
          path: ./valgring.log
